geo/urls.py
from django.urls import path, re_path, include
from geo.views import RegionShape

urlpatterns = [
    path('border', RegionShape.as_view()),
]

siriuso/urls.py
from django.urls import path, re_path, include #in new django 2.0 'url'=>'re_path'
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.http import response
from django.views.decorators.csrf import csrf_exempt

from graphene_django.views import GraphQLView
from registrado.api.schema import mutations

import pathlib


def graphiql(request):
    """Trivial view to serve the `graphiql.html` file."""
    del request
    graphiql_filepath = pathlib.Path(__file__).absolute().parent.parent / "main/templates/siriuso/graphiql.html"
    with open(graphiql_filepath) as f:
        return response.HttpResponse(f.read())


# GraphQL API
graphql_urls = [
    path('', GraphQLView.as_view(graphiql=settings.DEBUG)),
    path('registrado/', csrf_exempt(GraphQLView.as_view(graphiql=settings.DEBUG, schema=mutations))),
]

if settings.DEBUG:
    graphql_urls.append(path('ws/', graphiql))

urlpatterns = [
    # вход в админку
    path('admin/', admin.site.urls),
    # path('test/', main_views.Test.as_view(), name='test_page'),
    path('', include('django.contrib.auth.urls')),
    # GraphQL API
    path('api/v1.1/', include((graphql_urls, 'graphene_django'), namespace='api11')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# RocketChat Auth
urlpatterns += [re_path(r'^pim/', include('rocketchat_auth.urls'))]

forumoj/models.py
"""
Internacia Lingvo (Esperanto) https://tehnokom.su/il

Kopirajto © 2017 Teknokom https://tehnokom.su
Ĉi tiu dosiero estas parto de Teknokom Siriuso https://tehnokom.su/siriuso

Tiu ĉi programaro estas libera: vi povas distribui ĝin kaj/aŭ ŝanĝi ĝin laŭ
kondiĉoj de Ĝenerala Publika Licenco GNU publikigita per Libera Programara
Fonduso, aŭ laŭ la versio 3, aŭ (laŭ via bontrovo) laŭ ajna pli posta versio.

La programo estas distribuata esperante, ke ĝi utilos,
Sed SEN AJNAJ GARANTIOJ; sen anticipa garantio de KOMERCA VALORO aŭ TAŬGECO
POR CERTA CELO. Vidu GNU Ĝenerala Publika Licenco por ricevo de plua informo.

Vi devis ricevi la kopion de la publika ĝenerala licenco GNU kun tiu ĉi programo.
Se ne, do vidu https://www.gnu.org/licenses
"""

from django.db import models
from django.db.models import Max
from django.contrib.postgres import fields as pgfield
from django.utils.translation import ugettext_lazy as _
from django.contrib.postgres import fields as pgfields
from siriuso.models.postgres import CallableEncoder
from siriuso.utils import default_lingvo
from main.models import SiriusoBazaAbstraktaKomunumoj
from main.models import SiriusoKomentoAbstrakta
from main.models import SiriusoTipoAbstrakta, Uzanto
from komunumoj.models import KomunumojAliro, KomunumojForumo
from komunumoj.models import Komunumo
from informiloj.models import InformilojSciigoTipo
import sys


# Функционал форумов групп
# Типы категорий тем (справочник), использует абстрактный класс SiriusoTipoAbstrakta
class ForumojKategorioTipo(SiriusoTipoAbstrakta):

    # название в таблице названий типов, от туда будет браться название с нужным языковым тегом
    nomo = pgfields.JSONField(verbose_name=_('Nomo'), blank=True, null=False, default=default_lingvo,
                              encoder=CallableEncoder)

    # дополнительные настройки для модели
    class Meta:
        # название таблицы в базе данных для этой модели
        db_table = 'forumoj_kategorioj_tipoj'
        # читабельное название модели, в единственном числе
        verbose_name = _('Tipo de kategorioj')
        # читабельное название модели, во множественном числе
        verbose_name_plural = _('Tipoj de kategorioj')


# Категории тем групп, использует абстрактный класс SiriusoBazaAbstraktaKomunumoj
class ForumojKategorio(SiriusoBazaAbstraktaKomunumoj):

    # ID записи для вывода
    id = models.IntegerField(_('ID'), unique=True, default=0)

    # владелец (группа)
    posedanto = models.ForeignKey(Komunumo, verbose_name=_('Posedanto'), blank=True, null=True, default=None,
                                  on_delete=models.SET_NULL)
    # форум-владелец
    forumo = models.ForeignKey(KomunumojForumo, verbose_name=_('Mastro forumon'), blank=True,
                               null=True, on_delete=models.CASCADE)

    # тип категорий
    tipo = models.ForeignKey(ForumojKategorioTipo, verbose_name=_('Tipo'), blank=False, default=None,
                             on_delete=models.CASCADE)

    # название в таблице названий категорий, от туда будет браться название с нужным языковым тегом
    nomo = pgfields.JSONField(verbose_name=_('Titolo'), blank=True, null=False, default=default_lingvo,
                              encoder=CallableEncoder)

    # описание в таблице описаний категории, от туда будет браться описание с нужным языковым тегом
    priskribo = pgfields.JSONField(verbose_name=_('Priskribo'), blank=True, null=False, default=default_lingvo,
                                   encoder=CallableEncoder)

    # доступ к категории
    aliro = models.ForeignKey(KomunumojAliro, verbose_name=_('Aliro'), blank=False, default=None,
                              on_delete=models.CASCADE)

    # дополнительные настройки для модели
    class Meta:
        # название таблицы в базе данных для этой модели
        db_table = 'forumoj_kategorioj'
        # читабельное название модели, в единственном числе
        verbose_name = _('Kategorio')
        # читабельное название модели, во множественном числе
        verbose_name_plural = _('Kategorioj')

    # реализация автоинкремента при сохранении
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.id is None or not self.id:
            model = getattr(sys.modules[self.__module__], self.__class__.__name__)
            next_id = model.objects.all().aggregate(Max('id'))['id__max']

            if next_id is None:
                next_id = 1
            else:
                next_id = next_id + 1
            super(model, self).__setattr__('id', next_id)

        super(ForumojKategorio, self).save(force_insert=force_insert, force_update=force_update,
                                           using=using, update_fields=update_fields)


# Типы тем форума (справочник), использует абстрактный класс SiriusoTipoAbstrakta
class ForumojTemoTipo(SiriusoTipoAbstrakta):

    # название в таблице названий типов, от туда будет браться название с нужным языковым тегом
    nomo = pgfields.JSONField(verbose_name=_('Nomo'), blank=True, null=False, default=default_lingvo,
                              encoder=CallableEncoder)

    # дополнительные настройки для модели
    class Meta:
        # название таблицы в базе данных для этой модели
        db_table = 'forumoj_temoj_tipoj'
        # читабельное название модели, в единственном числе
        verbose_name = _('Tipo de temoj')
        # читабельное название модели, во множественном числе
        verbose_name_plural = _('Tipoj de temoj')


# Темы форумов групп, использует абстрактный класс SiriusoBazaAbstraktaKomunumoj
class ForumojTemo(SiriusoBazaAbstraktaKomunumoj):

    # ID записи для вывода
    id = models.IntegerField(_('ID'), unique=True, default=0)

    # владелец (группа)
    posedanto = models.ForeignKey(Komunumo, verbose_name=_('Posedanto'), blank=True, null=True, default=None,
                                  on_delete=models.CASCADE)

    # категория
    kategorio = models.ForeignKey(ForumojKategorio, verbose_name=_('Kategorio'), blank=False, default=None,
                                  on_delete=models.CASCADE)

    # тип темы
    tipo = models.ForeignKey(ForumojTemoTipo, verbose_name=_('Tipo'), blank=False, default=None,
                             on_delete=models.CASCADE)

    # название в таблице названий тем, от туда будет браться название с нужным языковым тегом
    nomo = pgfields.JSONField(verbose_name=_('Titolo'), blank=True, null=False, default=default_lingvo,
                              encoder=CallableEncoder)

    # текст в таблице текстов тем, от туда будет браться текст с нужным языковым тегом
    teksto = pgfields.JSONField(verbose_name=_('Teksto'), blank=True, null=False, default=default_lingvo,
                                encoder=CallableEncoder)

    # тема закрыта (да или нет)
    fermita = models.BooleanField(_('Fermita'), blank=False, default=False)

    # кому разрешено писать в закрытую тему
    komentado_aliro = models.ForeignKey(KomunumojAliro, verbose_name=_('Komentada aliro'), blank=False, default=None,
                                        on_delete=models.CASCADE)

    # тема закреплена (да или нет)
    fiksa = models.BooleanField(_('Fiksa'), blank=False, default=False)

    # позиция среди закреплённых тем
    fiksa_listo = models.IntegerField(_('Fiksa listo'), blank=True, null=True)

    # дополнительные настройки для модели
    class Meta:
        # название таблицы в базе данных для этой модели
        db_table = 'forumoj_temoj'
        # читабельное название модели, в единственном числе
        verbose_name = _('Temo')
        # читабельное название модели, во множественном числе
        verbose_name_plural = _('Temoj')

    # реализация автоинкремента при сохранении
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.id is None or not self.id:
            model = getattr(sys.modules[self.__module__], self.__class__.__name__)
            next_id = model.objects.all().aggregate(Max('id'))['id__max']

            if next_id is None:
                next_id = 1
            else:
                next_id = next_id + 1
            super(model, self).__setattr__('id', next_id)

        super(ForumojTemo, self).save(force_insert=force_insert, force_update=force_update,
                                      using=using, update_fields=update_fields)


# Комментарии тем форумов групп, использует абстрактный класс SiriusoKomentoAbstrakta
class ForumojTemoKomento(SiriusoKomentoAbstrakta):

    # владелец (тема)
    posedanto = models.ForeignKey(ForumojTemo, verbose_name=_('Posedanto'), blank=False, default=None,
                                  on_delete=models.CASCADE)

    # текст в таблице текстов комментариев тем, от туда будет браться текст с нужным языковым тегом
    teksto = pgfields.JSONField(verbose_name=_('Teksto'), blank=True, null=False, default=default_lingvo,
                                encoder=CallableEncoder)

    # дополнительные настройки для модели
    class Meta:
        # название таблицы в базе данных для этой модели
        db_table = 'forumoj_temoj_komentoj'


# Таблица истории посещений пользователями тем форумов
class ForumojUzantoHistorio(models.Model):
    # поле связи 1к1, одновременно и PK
    posedanto = models.OneToOneField(Uzanto, on_delete=models.CASCADE, primary_key=True)

    # JSON поле с ситорией посещений тем форумов
    historio = pgfield.JSONField(verbose_name=_('История посещений'), default=dict, blank=True)

    class Meta:
        db_table = 'forumoj_uzantoj_historioj'


# Таблица подписок пользователей на Темы форумов
class ForumojSciigoj(SiriusoBazaAbstraktaKomunumoj):
    # связь с темой форумов
    temo = models.ForeignKey(ForumojTemo, on_delete=models.CASCADE, blank=False, null=False)

    # тип способа уведомления
    sciigoj = models.ManyToManyField(InformilojSciigoTipo, verbose_name=_('Sciigo (muro)'), blank=True)

forumoj/views.py
"""
Internacia Lingvo (Esperanto) https://tehnokom.su/il

Kopirajto © 2017 Teknokom https://tehnokom.su
Ĉi tiu dosiero estas parto de Teknokom Siriuso https://tehnokom.su/siriuso

Tiu ĉi programaro estas libera: vi povas distribui ĝin kaj/aŭ ŝanĝi ĝin laŭ
kondiĉoj de Ĝenerala Publika Licenco GNU publikigita per Libera Programara
Fonduso, aŭ laŭ la versio 3, aŭ (laŭ via bontrovo) laŭ ajna pli posta versio.

La programo estas distribuata esperante, ke ĝi utilos,
Sed SEN AJNAJ GARANTIOJ; sen anticipa garantio de KOMERCA VALORO aŭ TAŬGECO
POR CERTA CELO. Vidu GNU Ĝenerala Publika Licenco por ricevo de plua informo.

Vi devis ricevi la kopion de la publika ĝenerala licenco GNU kun tiu ĉi programo.
Se ne, do vidu https://www.gnu.org/licenses
"""

forumoj/templates/forumoj/forumoj_organizo_novatemo.html
{# Internacia Lingvo (Esperanto) https://tehnokom.su/il #}

{# Kopirajto © 2017 Teknokom https://tehnokom.su #}
{# Ĉi tiu dosiero estas parto de Teknokom Siriuso https://tehnokom.su/siriuso #}

{# Tiu ĉi programaro estas libera: vi povas distribui ĝin kaj/aŭ ŝanĝi ĝin laŭ #}
{# kondiĉoj de Ĝenerala Publika Licenco GNU publikigita per Libera Programara #}
{# Fonduso, aŭ laŭ la versio 3, aŭ (laŭ via bontrovo) laŭ ajna pli posta versio. #}

{# La programo estas distribuata esperante, ke ĝi utilos, #}
{# Sed SEN AJNAJ GARANTIOJ; sen anticipa garantio de KOMERCA VALORO aŭ TAŬGECO #}
{# POR CERTA CELO. Vidu GNU Ĝenerala Publika Licenco por ricevo de plua informo. #}

{# Vi devis ricevi la kopion de la publika ĝenerala licenco GNU kun tiu ĉi programo. #}
{# Se ne, do vidu https://www.gnu.org/licenses #}

{% extends 'komunumoj/organizo.html' %}
{% load i18n %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block css_js2 %}
    <link href="{% static 'forumoj/style/forumoj.css' %}" rel="stylesheet">
{% endblock css_js2 %}
{% block title %}
    {% trans 'Kreado de nova temo' %} — {{ komunumo.nomo__enhavo }}
{% endblock title %}
{% block komunumo_side %}
    {% block menuo %}
        {% include 'komunumoj/komunumoj_organizo_menuo.html' with forumo=True %}
    {% endblock menuo %}
    <div class="forumoj_chiuj">
        <div class="forumoj_adreso_bloko">
            <div class="forumoj_adreso_bloko_vorto">
                <a href="{% url 'forumoj:forumoj_kategorio_listo' kom_tipo=kom_tipo kom_id=komunumo.id %}">{% trans 'Forumo de Organizo' %}</a>&nbsp>&nbsp
                <a href="{% url 'forumoj:forumoj_temo_listo' kom_tipo=kom_tipo kom_id=komunumo.id kategorio_id=kategorio.id %}">{{ kategorio.nomo__enhavo }}</a>&nbsp>
                <span class="forumoj_teksta_butono">{% trans 'Kreado de nova temo' %}</span>
            </div>
        </div>
    </div>
    <div class="forumoj_chiuj">
    <div class="forumoj_chiuj_bloko">


        <form method="POST" class="temo-formo"  action="{% url 'forumoj:forumoj_novatemo' kom_tipo=kom_tipo kom_id=komunumo.id kategorio_id=kategorio.id %}">
        {% csrf_token %}
        {{ formo.media }}
        {{ formo.posedanto }}
        {{ formo.kategorio }}
        {{ formo.autoro }}
        <ul class="forumoj_listo">
            <li class="forumoj_listo_item">
                <a href="{% url 'muroj:muro_uzanto' uzanto_id=a_uzanto.id %}" title="{{ a_uzanto.unua_nomo__enhavo }} {{ a_uzanto.familinomo__enhavo }}">
                    <div class="forumoj_listo_item_image">
                        {% if a_uzanto.uzantojavataro__bildo_min %}
                            <img src="/media/{{ a_uzanto.uzantojavataro__bildo_min }}">
                        {% else %}
                            {% if a_uzanto.autoro__sekso == 'vira' or a_uzanto.autoro__sekso is None %}
                                <img src="{% static 'main/images/vira-avataro-min.png' %}">
                            {% else %}
                                <img src="{% static 'main/images/virina-avataro-min.png' %}">
                            {% endif %}
                        {% endif %}
                    </div>
                </a>
                <div class="forumoj_listo_item_teksto">
                <div class="forumoj_komento_enhavo">
                    <input type="hidden" name="ago" value="kategorio"/>
                    <div class="forumoj_komento_teksto">
                        {% if formo.non_field_errors %}
                        <ul>
                            {% for error in formo.non_field_errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <p>{{ formo.nomo_formo }}</p>
                        <small>{{ formo.small.errors }}</small>
                        <p>{{ formo.teksto_formo }}</p>
                        <small>{{ formo.teksto.errors }}</small>
                        <p>{% trans 'Tipo' %}&nbsp;&nbsp;{{ formo.tipo }}&nbsp;&nbsp;&nbsp;{% trans 'Aliro' %}&nbsp;&nbsp;{{ formo.komentado_aliro }}&nbsp;&nbsp;&nbsp;<label for="id_fiksa">Закрепить тему</label>{{ formo.fiksa }}</p>
                    </div>
                    <div class="forumoj_komento_butono">
                    <button class="submit">{% trans 'Publikigi' %}</button>
                    </div>
                </div>
                </div>

            </li>
        </ul>
        </form>


    </div>
    </div>
{% endblock komunumo_side %}

forumoj/templates/forumoj/forumoj_sociaprojekto_novakategorio.html
{# Internacia Lingvo (Esperanto) https://tehnokom.su/il #}

{# Kopirajto © 2017 Teknokom https://tehnokom.su #}
{# Ĉi tiu dosiero estas parto de Teknokom Siriuso https://tehnokom.su/siriuso #}

{# Tiu ĉi programaro estas libera: vi povas distribui ĝin kaj/aŭ ŝanĝi ĝin laŭ #}
{# kondiĉoj de Ĝenerala Publika Licenco GNU publikigita per Libera Programara #}
{# Fonduso, aŭ laŭ la versio 3, aŭ (laŭ via bontrovo) laŭ ajna pli posta versio. #}

{# La programo estas distribuata esperante, ke ĝi utilos, #}
{# Sed SEN AJNAJ GARANTIOJ; sen anticipa garantio de KOMERCA VALORO aŭ TAŬGECO #}
{# POR CERTA CELO. Vidu GNU Ĝenerala Publika Licenco por ricevo de plua informo. #}

{# Vi devis ricevi la kopion de la publika ĝenerala licenco GNU kun tiu ĉi programo. #}
{# Se ne, do vidu https://www.gnu.org/licenses #}

{% extends 'komunumoj/sociaprojekto.html' %}
{% load i18n %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block css_js2 %}
    <link href="{% static 'forumoj/style/forumoj.css' %}" rel="stylesheet">
{% endblock css_js2 %}
{% block title %}
    {% trans 'Kreado de nova kategorio' %} — {{ komunumo.nomo__enhavo }}
{% endblock title %}
{% block komunumo_side %}
    {% block menuo %}
        {% include 'komunumoj/komunumoj_sociaprojekto_menuo.html' with forumo=True %}
    {% endblock menuo %}
    <div class="forumoj_chiuj">
        <div class="forumoj_adreso_bloko">
            <div class="forumoj_adreso_bloko_vorto">
                <a href="{% url 'forumoj:forumoj_kategorio_listo' kom_tipo=kom_tipo kom_id=komunumo.id %}">
                    {% trans 'Forumo de Soveto' %}
                </a>&nbsp>
                <span class="forumoj_teksta_butono">{% trans 'Kreado de nova kategorio' %}</span>

            </div>
        </div>
    </div>
    <div class="forumoj_chiuj">
    <div class="forumoj_chiuj_bloko">


        <form method="POST" class="kategorio-formo" action="{% url 'forumoj:forumoj_novakategorio' kom_tipo=kom_tipo kom_id=komunumo.id %}">
        {% csrf_token %}
        <input name="posedanto" id="id_posedanto" value="{{ komunumo.uuid }}" type="hidden" >
        <input name="autoro" id="id_autoro" value="{{ user.id }}" type="hidden" >
        <ul class="forumoj_listo">
            <li class="forumoj_listo_item">
                <a href="{% url 'muroj:muro_uzanto' uzanto_id=a_uzanto.id %}" title="{{ a_uzanto.unua_nomo__enhavo }} {{ a_uzanto.familinomo__enhavo }}">
                    <div class="forumoj_listo_item_image">
                        {% if a_uzanto.uzantojavataro__bildo_min %}
                            <img src="/media/{{ a_uzanto.uzantojavataro__bildo_min }}">
                        {% else %}
                            {% if a_uzanto.autoro__sekso == 'vira' or a_uzanto.autoro__sekso is None %}
                                <img src="{% static 'main/images/vira-avataro-min.png' %}">
                            {% else %}
                                <img src="{% static 'main/images/virina-avataro-min.png' %}">
                            {% endif %}
                        {% endif %}
                    </div>
                </a>
                <div class="forumoj_listo_item_teksto">
                <div class="forumoj_komento_enhavo">
                    <input type="hidden" name="ago" value="kategorio"/>
                    <div class="forumoj_komento_teksto">
                        {% if formo.non_field_errors %}
                        <ul>
                            {% for error in formo.non_field_errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <p class="forumoj_katigorio_nomo">{{ formo.nomo }}</p>
                        <small>{{ formo.nomo.errors }}</small>
                        <p>{{ formo.priskribo }}</p>
                        <small>{{ formo.priskribo.errors }}</small>
                        <p>{% trans 'Tipo' %} {{ formo.tipo }}&nbsp;&nbsp;&nbsp;{% trans 'Aliro' %} {{ formo.aliro }}</p>
                    </div>
                    <div class="forumoj_komento_butono">
                    <button class="submit">{% trans 'Publikigi' %}</button>
                    </div>
                </div>
                </div>

            </li>
        </ul>
        </form>


    </div>
    </div>
{% endblock komunumo_side %}

forumoj/templates/forumoj/forumoj_sociaprojekto_novatemo.html
{# Internacia Lingvo (Esperanto) https://tehnokom.su/il #}

{# Kopirajto © 2017 Teknokom https://tehnokom.su #}
{# Ĉi tiu dosiero estas parto de Teknokom Siriuso https://tehnokom.su/siriuso #}

{# Tiu ĉi programaro estas libera: vi povas distribui ĝin kaj/aŭ ŝanĝi ĝin laŭ #}
{# kondiĉoj de Ĝenerala Publika Licenco GNU publikigita per Libera Programara #}
{# Fonduso, aŭ laŭ la versio 3, aŭ (laŭ via bontrovo) laŭ ajna pli posta versio. #}

{# La programo estas distribuata esperante, ke ĝi utilos, #}
{# Sed SEN AJNAJ GARANTIOJ; sen anticipa garantio de KOMERCA VALORO aŭ TAŬGECO #}
{# POR CERTA CELO. Vidu GNU Ĝenerala Publika Licenco por ricevo de plua informo. #}

{# Vi devis ricevi la kopion de la publika ĝenerala licenco GNU kun tiu ĉi programo. #}
{# Se ne, do vidu https://www.gnu.org/licenses #}

{% extends 'komunumoj/sociaprojekto.html' %}
{% load i18n %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block css_js2 %}
    <link href="{% static 'forumoj/style/forumoj.css' %}" rel="stylesheet">
{% endblock css_js2 %}
{% block title %}
    {% trans 'Kreado de nova temo' %} — {{ komunumo.nomo__enhavo }}
{% endblock title %}
{% block komunumo_side %}
    {% block menuo %}
        {% include 'komunumoj/komunumoj_sociaprojekto_menuo.html' with forumo=True %}
    {% endblock menuo %}
    <div class="forumoj_chiuj">
        <div class="forumoj_adreso_bloko">
            <div class="forumoj_adreso_bloko_vorto">
                <a href="{% url 'forumoj:forumoj_kategorio_listo' kom_tipo=kom_tipo kom_id=komunumo.id %}">{% trans 'Forumo de Sociaprojekto' %}</a>&nbsp>&nbsp
                <a href="{% url 'forumoj:forumoj_temo_listo' kom_tipo=kom_tipo kom_id=komunumo.id kategorio_id=kategorio.id %}">{{ kategorio.nomo__enhavo }}</a>&nbsp>
                <span class="forumoj_teksta_butono">{% trans 'Kreado de nova temo' %}</span>
            </div>
        </div>
    </div>
    <div class="forumoj_chiuj">
    <div class="forumoj_chiuj_bloko">


        <form method="POST" class="temo-formo"  action="{% url 'forumoj:forumoj_novatemo' kom_tipo=kom_tipo kom_id=komunumo.id kategorio_id=kategorio.id %}">
        {% csrf_token %}
        {{ formo.media }}
        {{ formo.posedanto }}
        {{ formo.kategorio }}
        {{ formo.autoro }}
        <ul class="forumoj_listo">
            <li class="forumoj_listo_item">
                <a href="{% url 'muroj:muro_uzanto' uzanto_id=a_uzanto.id %}" title="{{ a_uzanto.unua_nomo__enhavo }} {{ a_uzanto.familinomo__enhavo }}">
                    <div class="forumoj_listo_item_image">
                        {% if a_uzanto.uzantojavataro__bildo_min %}
                            <img src="/media/{{ a_uzanto.uzantojavataro__bildo_min }}">
                        {% else %}
                            {% if a_uzanto.autoro__sekso == 'vira' or a_uzanto.autoro__sekso is None %}
                                <img src="{% static 'main/images/vira-avataro-min.png' %}">
                            {% else %}
                                <img src="{% static 'main/images/virina-avataro-min.png' %}">
                            {% endif %}
                        {% endif %}
                    </div>
                </a>
                <div class="forumoj_listo_item_teksto">
                <div class="forumoj_komento_enhavo">
                    <input type="hidden" name="ago" value="kategorio"/>
                    <div class="forumoj_komento_teksto">
                        {% if formo.non_field_errors %}
                        <ul>
                            {% for error in formo.non_field_errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <p>{{ formo.nomo_formo }}</p>
                        <small>{{ formo.small.errors }}</small>
                        <p>{{ formo.teksto_formo }}</p>
                        <small>{{ formo.teksto.errors }}</small>
                        <p>{% trans 'Tipo' %}&nbsp;&nbsp;{{ formo.tipo }}&nbsp;&nbsp;&nbsp;{% trans 'Aliro' %}&nbsp;&nbsp;{{ formo.komentado_aliro }}&nbsp;&nbsp;&nbsp;<label for="id_fiksa">Закрепить тему</label>{{ formo.fiksa }}</p>
                    </div>
                    <div class="forumoj_komento_butono">
                    <button class="submit">{% trans 'Publikigi' %}</button>
                    </div>
                </div>
                </div>

            </li>
        </ul>
        </form>


    </div>
    </div>
{% endblock komunumo_side %}